server:
  port: 8000
  servlet:
    context-path: /hyd-server
  http2:
    # 启用 HTTP/2 支持，提升传输效率
    enabled: true
  compression:
    # 启用 GZIP 压缩，减少传输数据量
    enabled: true
    # 需要压缩的 MIME 类型
    mime-types: text/html, text/xml, text/plain, application/json

spring:
  freemarker:
    check-template-location: false

  #配置 Jpa
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: cn.wuhan.hyd.framework.config.CustomPhysicalNamingStrategy
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.p6spy.engine.spy.P6SpyDriver
      url: jdbc:p6spy:mysql://113.44.83.240:3306/hyd?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: hyd
      password: F5TJhWFeaPkEMzCL
      # 初始连接数，建议设置为与最小空闲连接数相同
      initial-size: 20
      # 最小空闲连接数，保持足够的空闲连接以应对请求
      min-idle: 20
      # 最大连接数，根据并发需求适当增加
      max-active: 50
      # 获取连接超时时间（毫秒），调整以满足响应时间要求
      max-wait: 3000
      # 启用KeepAlive机制，保持长连接
      keep-alive: true
      # 连接有效性检测间隔时间（毫秒），定期检查连接的健康状态
      time-between-eviction-runs-millis: 60000
      # 连接在池中最小生存时间（毫秒），确保连接在池中至少存在一段时间
      min-evictable-idle-time-millis: 300000
      # 连接在池中最大生存时间（毫秒），防止连接在池中停留过长
      max-evictable-idle-time-millis: 900000
      # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除
      test-while-idle: true
      # 指明是否在从池中取出连接前进行检验,如果检验失败, 则从池中去除连接并尝试取出另一个
      test-on-borrow: true
      # 是否在归还到池中前进行检验
      test-on-return: false
      # 停用 com_ping 探活机制
      use-ping-method: false
      # 检测连接是否有效
      validation-query: SELECT 1
      # 配置监控统计
      webStatFilter:
        enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
      filter:
        stat:
          enabled: true
          # 记录慢SQL
          log-slow-sql: true
          slow-sql-millis: 2000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
#是否开启 swagger-ui
swagger:
  enabled: true
#jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/毫秒 ，默认4小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 14400000
  # 在线用户key
  online-key: "online_token:"
  # 验证码
  code-key: "captcha_code:"
  # token 续期检查时间范围（默认30分钟，单位毫秒），在token即将过期的一段时间内用户操作了，则给用户的token续期
  detect: 1800000
  # 续期时间范围，默认1小时，单位毫秒
  renew: 3600000
# 文件存储路径
file:
  mac:
    path: ~/file/
    avatar: ~/avatar/
  linux:
    path: /home/sports/file/
    avatar: /home/sports/avatar/
  windows:
    path: C:\sports\file\
    avatar: C:\sports\avatar\
  # 文件大小 /M
  maxSize: 100
  avatarMaxSize: 5

logging:
  level:
    root: INFO
